### ISSUE TITLE
getting java.net.connectException when running the Mamba scheduler to populate analysis_db

### ISSUE THREAD

**Issue by satyadeep-ih** [UCSF-IGHS/openmrs-module-ohri-mamba#31]
Hi @smallgod , @GOmare  

I have installed the module on #**OpenMRS core 2.4** and **MySQL 8.0** on **Ubuntu 20** with **Tomcat 8** and **OpenJDK 8**

When the scheduler to populate analysis_db is run it is not able to connect to DB as per following screenshot: 

![image](https://github.com/UCSF-IGHS/openmrs-module-ohri-mamba/assets/74664078/042cf2f4-d352-4a6a-89cf-3193e44601ea)

My configuration for the scheduler is:
![Screenshot 2024-02-01 180501](https://github.com/UCSF-IGHS/openmrs-module-ohri-mamba/assets/74664078/b2f7087b-5644-4458-9892-22cf1a57cf8e)

![Screenshot 2024-02-01 180440](https://github.com/UCSF-IGHS/openmrs-module-ohri-mamba/assets/74664078/d915b308-a1d0-4684-8b03-1a8dbdf9e5ca)

Which file should I check in for this?

My `**mamba/config.xml** `has following properties: 

```
    <globalProperty>
        <property>mambaetl.analysis.db.url</property>
        <defaultValue>jdbc:mysql://db:3306/analysis_db?autoReconnect=true</defaultValue>
        <description>MambaETL JDBC Connection string
        </description>
    </globalProperty>

    <globalProperty>
        <property>mambaetl.analysis.db.username</property>
        <defaultValue>root</defaultValue>
        <description>MambaETL username</description>
    </globalProperty>

    <globalProperty>
        <property>mambaetl.analysis.db.password</property>
        <defaultValue>i10hi1c</defaultValue>
        <description>MambaETL user password</description>
    </globalProperty>

    <globalProperty>
        <property>mambaetl.analysis.db.driver</property>
        <defaultValue>com.mysql.jdbc.Driver</defaultValue>
        <description>MambaETL JDBC driver</description>
    </globalProperty>

```

**Comment by satyadeep-ih** [comment]
Anything on this @smallgod @GOmare @larslemos

**Comment by GOmare** [comment]
@satyadeep-ih Is your pom.xml on ohri mamba have the following 
![image](https://github.com/UCSF-IGHS/openmrs-module-ohri-mamba/assets/25583672/096e575f-996c-461c-a62d-a65adf0c02fb)
cc: @smallgod @alaboso

**Comment by satyadeep-ih** [comment]
![image](https://github.com/UCSF-IGHS/openmrs-module-ohri-mamba/assets/74664078/41ae8808-5b3c-4f34-aa36-3db357462dce)
@GOmare  this is what I have in pom.xml

**Comment by GOmare** [comment]
@satyadeep-ih  are you on slack?

**Comment by satyadeep-ih** [comment]
HI @GOmare , yes I am at satyadeep@intelehealth.io

**Comment by GOmare** [comment]
on Openmrs, MambaETL channel?

**Comment by satyadeep-ih** [comment]
NO can you send me an invite

**Comment by satyadeep-ih** [comment]
This is fixed by setting correct value for **mambaetl.analysis.db.url** in global_property table of openmrs
